"""Ephemeral stream coordination, separate from durable history and billing."""
from typing import Protocol, Any


class StreamManager(Protocol):
    def set_live_run(self, session_id: str, run_id: str, owner: str) -> bool: ...
    def get_live_run(self, session_id: str) -> dict[str, str] | None: ...
    def clear_live_run(self, session_id: str, run_id: str, owner: str) -> bool: ...
    def renew_live_run(self, session_id: str, run_id: str, owner: str) -> bool: ...
    def append_event(self, session_id: str, run_id: str, event: dict[str, Any]) -> None: ...
    def get_events(self, session_id: str, run_id: str, after_seq: int) -> list[dict[str, Any]]: ...
